/* generated by Gemini 2.5 Pro */
#ifndef CACHE_SIMULATOR_H
#define CACHE_SIMULATOR_H

#include <stdint.h>
#include <stdbool.h>

// 用于表示一个缓存行
typedef struct {
    bool valid;
    uint64_t tag;
} CacheLine;

// 缓存模拟器的状态结构体
typedef struct {
    uint64_t num_sets;
    uint64_t num_ways;
    uint64_t cacheline_size;

    uint64_t offset_bits;
    uint64_t index_bits;

    CacheLine** cache_store; // 缓存实体: 指向指针的指针，模拟二维数组
    uint64_t** lru_queues;   // LRU状态队列: 用数组模拟，0为MRU, num_ways-1为LRU

    bool coherent; // 是否为 cache coherence
} CacheSimulator;

/**
 * @brief 创建并初始化一个缓存模拟器实例
 * @param sets 缓存组数 (必须是2的幂)
 * @param ways 每个组的关联度 (路数)
 * @param cacheline_size 缓存行大小，单位字节 (必须是2的幂)
 * @param coherent 是否启用 coherence 相关标志（记录用途，具体逻辑由上层使用）
 * @return 成功则返回指向CacheSimulator的指针，失败则返回NULL
 */
CacheSimulator* cache_simulator_create(uint64_t sets, uint64_t ways, uint64_t cacheline_size, bool coherent);

/**
 * @brief 销毁缓存模拟器实例，释放所有分配的内存
 * @param sim 指向要销毁的CacheSimulator实例的指针
 */
void cache_simulator_destroy(CacheSimulator* sim);

/**
 * @brief 处理一次内存访问
 * @param sim 指向CacheSimulator实例的指针
 * @param address 访问的64位物理地址
 * @param miss_address [输出参数] 如果发生未命中，这里将被填充为需要向L2请求的地址
 * @return 如果是缓存命中(Hit)则返回true，如果是未命中(Miss)则返回false
 */
bool cache_simulator_access(CacheSimulator* sim, uint64_t address, uint64_t* miss_address);

/**
 * @brief 将指定地址对应的缓存行从缓存中驱逐（invalidate）
 * @param sim 指向CacheSimulator实例的指针
 * @param address 要驱逐的64位物理地址
 * @return 如果找到并使缓存行无效则返回true，否则返回false
 */
bool cache_simulator_evict(CacheSimulator* sim, uint64_t address);

#endif // CACHE_SIMULATOR_H